### ISSUE TITLE
Changes related to POST component

### ISSUE THREAD

**Issue by razak571** [SNEHASIS-CODEHUB04/IdeaScape#1]
This issue I am creating to resolve @SNEHASIS-CODEHUB04  's issue on creating the post on Appwrite. It has issue in Appwrite and also in code level.

**Comment by razak571** [comment]
this issue can be closed now #2  @SNEHASIS-CODEHUB04

**Comment by SNEHASIS-CODEHUB04** [comment]
new commits

**Comment by SNEHASIS-CODEHUB04** [comment]
Done

**Comment by SNEHASIS-CODEHUB04** [comment]
new Commits
